### ISSUE TITLE
Trouble with node 0.6.7

### ISSUE THREAD

**Issue by rpledge** [dekz/dcrypt#11]
Not sure if this module is still supported, but I'm having trouble trying to use it with node 0.6.7.  I'd try and debug it but node is pretty new to me.

 npm install dcrypt

npm http GET https://registry.npmjs.org/dcrypt
npm http 304 https://registry.npmjs.org/dcrypt

npm ERR! Error: No compatible version found: dcrypt
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/local/lib/node_modules/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:415:44)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:408:5
npm ERR!     at Object.saved [as oncomplete](/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "dcrypt"
npm ERR! cwd /Users/rpledge/dcryptTest
npm ERR! node -v v0.6.7
npm ERR! npm -v 1.1.0-2
npm ERR! message No compatible version found: dcrypt
npm ERR! message No valid targets found.
npm ERR! message Perhaps not compatible with your version of node?
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/rpledge/dcryptTest/npm-debug.log
npm not ok

**Comment by dekz** [comment]
You may try forcing it to install, I haven't tested since version 0.5.0.

Do a git clone of the repo and change the pakage.json line 36 to 
`"node": ">= 0.4.2 <= 0.6.7"`
Then perform an
   `npm install .`

**Comment by rpledge** [comment]
Thanks, that helped.  I had to adjust the dcrypt.coffee file as well, maybe some default paths have changed?  The changes below made the package work for me (well, the function I needed at least).  Any chance you could push an updated version to npmjs.org?

``` diff

diff --git a/dcrypt.coffee b/dcrypt.coffee
index 265e3cb..446d6fc 100644
--- a/dcrypt.coffee
+++ b/dcrypt.coffee
@@ -1,4 +1,4 @@
-_bindings = require './build/default/dcrypt'
+_bindings = require './build/Release/dcrypt'

 #OpenSSL bindings for Node.js. This module extends what is in node-crypto bringing much needed additiona
 Random = _bindings.Random
diff --git a/package.json b/package.json
index 0315b10..885f19b 100644
--- a/package.json
+++ b/package.json
@@ -33,7 +33,7 @@
     "coffee-script": ">= 0.9.5 < 1.1.0"
   },
   "engines": {
-    "node": ">= 0.4.2 < 0.5.0",
+    "node": ">= 0.4.2 < 0.6.7",
     "npm": ">= 0.3.15 < 1.1.0"
   }
 }
\ No newline at end of file
```
